### ISSUE TITLE
`PSP34::Id` enum technical overhead

### ISSUE THREAD

**Issue by boyswan** [Brushfam/openbrush-contracts#53]
Currently `PSP34::Id` is an enum of data types `u8, u16, ..., bytes`. Whilst this provides a degree of flexibility in being able to use smaller sized integers for ids, the trade-off technical cost is very large.

Having to handle all cases for enums is very unwieldy, and in the majority of cases users are going to default to a `U32`. 

An example trying to create an incremental `PSP34::Id` in rmrk-ink

```rust
  fn inc(&mut self) -> Result<Id> {
        *self = match self {
            Id::U8(id) => id.checked_add(1).map(Id::U8),
            Id::U16(id) => id.checked_add(1).map(Id::U16),
            Id::U32(id) => id.checked_add(1).map(Id::U32),
            Id::U64(id) => id.checked_add(1).map(Id::U64),
            Id::U128(id) => id.checked_add(1).map(Id::U128),
            Id::Bytes(_) => panic!("bytes id increment unsupported"),
        }
        .ok_or(Error::Rmrk(RmrkError::Overflow))?; 
        Ok(self.clone())
    }
 ```
 
Handling bytes is too troublesome. I'm also dealing with a lot of overhead handling `PSP34::Id` in events via subsquid, making sure Ids are not being created on the fly from regular ints,  etc.
 
This issue is more of a point of discussion with the team to understand their decision. From my perspective, I would much rather sacrifice a few bytes and have ids as `Id(u32)`, and avoid all the overhead.

**Comment by PierreOssun** [comment]
The reason we add this enum with those values is to be sure the standards meets any requirements. 
- If you want a PSP34 compatible with Solidity ERC721s that use `uint256` as id then [u8; 32] is needed (there is no enum like this in ERC721 as all types are 256bits anyways)
- `u128` is easily interfaced with Balance
- any other type for storage efficiency

Enforcing one type (u32 for example) might restrict some projects to use PSP34 and have to create a variant of it.

The best way would be to implement Traits for `Id` enum in OpenBrush so that it can lower the "troublesomeness". Can you list what is needed from you side to be implemented (except `inc()`) ?.
For event via Subsquid indexer It would be great to provide a library so that anyone can index PSP34s easily (and maybe other PSPs ?)

**Comment by boyswan** [comment]
Makes sense - good point on the EVM `uint256`! 

There's not any particular functionality (other than incrementing) that I can think of right now - if I come across any other examples I'll make a new issue.

Thanks for the response, this helps clear a lot of things up.
